function [fitresult, gof] = createFits(t0, theta0, t1, theta1, t2, theta2, t3, theta3, t4, theta4, t5, theta5)
%CREATEFITS(T0,THETA0,T1,THETA1,T2,THETA2,T3,THETA3,T4,THETA4,T5,THETA5)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t0
%      Y Output: theta0
%  Data for 'untitled fit 2' fit:
%      X Input : t1
%      Y Output: theta1
%  Data for 'untitled fit 3' fit:
%      X Input : t2
%      Y Output: theta2
%  Data for 'untitled fit 4' fit:
%      X Input : t3
%      Y Output: theta3
%  Data for 'untitled fit 5' fit:
%      X Input : t4
%      Y Output: theta4
%  Data for 'untitled fit 6' fit:
%      X Input : t5
%      Y Output: theta5
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2019 14:14:07

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 6, 1 );
gof = struct( 'sse', cell( 6, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t0, theta0 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-2.35*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -1 -Inf];
opts.StartPoint = [0.0647828627672011 0.135278820878134 0.959492426392903];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'theta0 vs. t0', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t0
ylabel theta0
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( t1, theta1 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-7.51*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.54179626886419 0.245243514653417 0.655740699156587];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'theta1 vs. t1', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
xlabel t1
ylabel theta1
grid on

%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( t2, theta2 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-5.24*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.163239579344391 0.651258002376558 0.933993247757551];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'theta2 vs. t2', 'untitled fit 3', 'Location', 'NorthEast' );
% Label axes
xlabel t2
ylabel theta2
grid on

%% Fit: 'untitled fit 4'.
[xData, yData] = prepareCurveData( t3, theta3 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-40*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.157685332950402 0.177222699708518 0.678735154857773];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 4' );
h = plot( fitresult{4}, xData, yData );
legend( h, 'theta3 vs. t3', 'untitled fit 4', 'Location', 'NorthEast' );
% Label axes
xlabel t3
ylabel theta3
grid on

%% Fit: 'untitled fit 5'.
[xData, yData] = prepareCurveData( t4, theta4 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-120*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.861261680137404 0.8508 0.757740130578333];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 5' );
h = plot( fitresult{5}, xData, yData );
legend( h, 'theta4 vs. t4', 'untitled fit 5', 'Location', 'NorthEast' );
% Label axes
xlabel t4
ylabel theta4
grid on

%% Fit: 'untitled fit 6'.
[xData, yData] = prepareCurveData( t5, theta5 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-250*x+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.522475180580616 0.944231982313085 0.743132468124916];
opts.Upper = [Inf 0 Inf];

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 6' );
h = plot( fitresult{6}, xData, yData );
legend( h, 'theta5 vs. t5', 'untitled fit 6', 'Location', 'NorthEast' );
% Label axes
xlabel t5
ylabel theta5
grid on


